'use strict';function v(f,a,b,d){f.u.uc(f.ab,a,b,d,void 0)}function E(f,a,b,d){f.u.ca?v(f,a,b,d):f.u.yf()._OnMessageFromDOM({type:"event",component:f.ab,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function I(f,a,b){f.u.C(f.ab,a,b)}function K(f,a){for(const [b,d]of a)I(f,b,d)}function L(f){f.Ub||(f.u.gf(f.pe),f.Ub=!0)}window.Sa=class{constructor(f,a){this.u=f;this.ab=a;this.Ub=!1;this.pe=()=>this.wa()}pd(){}wa(){}};function N(f){-1!==f.Qa&&(self.clearTimeout(f.Qa),f.Qa=-1)}
window.Xe=class{constructor(f,a){this.Uc=f;this.Ug=a;this.Qa=-1;this.Vb=-Infinity;this.qe=()=>{this.Qa=-1;this.Vb=Date.now();this.gb=!0;this.Uc();this.gb=!1};this.Vd=this.gb=!1}f(){N(this);this.qe=this.Uc=null}};"use strict";function O(f,a){I(f,"get-element",b=>{const d=f.ba.get(b.elementId);return a(d,b)})}
window.ph=class extends self.Sa{constructor(f,a){super(f,a);this.ba=new Map;this.Tc=!0;K(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ba.get(b);this.Tc&&d.parentElement.removeChild(d);this.ba.delete(b)}}],["set-visible",b=>{this.Tc&&(this.ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Tc){var d=this.ba.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ba.get(b.elementId);throw Error("required override");}],["focus",b=>this.Nc(b)],["set-css-style",b=>{this.ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ba.get(b.elementId).removeAttribute(b.name)}]]);O(this,b=>b)}Nc(f){var a=this.ba.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function d(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.fh?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;c.textContent=m.jh+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let h=!1,n=!1;function q(){if(!h){try{new Worker("blob://",{get type(){n=
!0}})}catch(m){}h=!0}return n}let w=new Audio;const B={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function D(m){m=await x(m);return(new TextDecoder("utf-8")).decode(m)}
function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const y=[];let C=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let J=0;const M=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");M.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let g=!1;window.va=class m{constructor(c){this.ca=c.lh;this.qa=null;this.F="";this.ic=c.ih;
this.wb={};this.Ja=this.vb=null;this.Sb=[];this.G=this.Oa=null;this.ae=!1;this.jb=null;this.Na=-1;this.Zg=()=>this.bg();this.Ma=[];this.s=c.re;this.hb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&q()||(this.ca=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ca=!1;if("cordova"===this.s&&this.ca)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ca=!1)}else this.ca=!1;this.Yb=this.ia=
null;"html5"!==this.s&&"playable-ad"!==this.s||!this.hb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",k=>this.Gf(k));
this.C("runtime","create-job-worker",()=>this.Hf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Id(c)):this.Id(c)}f(){this.Ac();this.qa&&(this.qa=this.qa.onmessage=null);this.vb&&(this.vb.terminate(),this.vb=null);this.Ja&&(this.Ja.f(),this.Ja=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}Se(){return f&&"cordova"===this.s}tc(){const c=navigator.userAgent;return f&&e.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}Qe(){return a}wd(){return a&&
e.has(this.s)}async Id(c){"macos-wkwebview"===this.s&&this.Rc({type:"ready"});if("playable-ad"===this.s){this.ia=self.c3_base64files;this.Yb={};await this.mf();for(let l=0,p=c.Ra.length;l<p;++l){var k=c.Ra[l].toLowerCase();this.Yb.hasOwnProperty(k)?c.Ra[l]={fh:!0,jh:this.Yb[k]}:this.ia.hasOwnProperty(k)&&(c.Ra[l]=URL.createObjectURL(this.ia[k]))}}c.$g?this.F=c.$g:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));
c.nh&&(this.wb=c.nh);k=new MessageChannel;this.qa=k.port1;this.qa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Yf(l));this.jb=new self.Te(this);await P(this.jb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.Bf(c,k.port2):await this.Af(c,k.port2)}Dc(c){c=this.wb.hasOwnProperty(c)?this.wb[c]:c.endsWith("/workermain.js")&&
this.wb.hasOwnProperty("workermain.js")?this.wb["workermain.js"]:"playable-ad"===this.s&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async nc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.hb)return c=await this.yb(l.eh?c:this.ic+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}oa(){return Math.max(window.innerWidth,1)}fa(){return Math.max(window.innerHeight,1)}Gd(c){var k=this.jb;return{baseUrl:this.F,previewUrl:location.href,windowInnerWidth:this.oa(),windowInnerHeight:this.fa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Va(),projectData:c.vh,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.th||"",exportType:c.re,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.uh,jobScheduler:{inputPort:k.ad,outputPort:k.hd,maxNumWorkers:k.Wg},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ic+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ic+"opus.wasm.wasm",isFileProtocol:this.hb,isiOSCordova:this.Se(),isiOSWebView:this.tc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Bf(c,k){var l=this.Dc(c.mh);this.vb=
await this.nc(l,this.F,{type:"module",name:"Runtime",eh:!0});this.G=document.createElement("canvas");this.G.style.display="none";l=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;let p=c.od||[],u=c.Ra;p=await Promise.all(p.map(r=>this.Ea(r)));u=await Promise.all(u.map(r=>this.Ea(r)));if("cordova"===this.s)for(let r=0,t=c.lc.length;r<t;++r){const z=c.lc[r],H=z[0];if(H===c.md||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))z[1]=await this.Ea(H)}this.vb.postMessage(Object.assign(this.Gd(c),
{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.lc,mainProjectScript:c.md,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...Q(this.jb)]);this.Sb=F.map(r=>new r(this));this.Fd();self.c3_callFunction=(r,t)=>this.Oa.Cf(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.uc("runtime","go-to-last-error-script"))}async Af(c,k){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);
window.c3canvas=this.G;this.Sb=F.map(r=>new r(this));this.Fd();var l=c.Ra.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.od)&&l.unshift(...c.od);l=await Promise.all(l.map(r=>this.Ea(r)));await Promise.all(l.map(r=>d(r)));l=self.C3_ProjectScriptsStatus;const p=c.md,u=c.lc;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Ea(t),await d(t),"preview"!==this.s||l[r]||this.Qd(r,"main script did not run to completion")}catch(z){this.Qd(r,z)}else if("scriptsInEvents.js"===
r||r.endsWith("/scriptsInEvents.js"))t=await this.Ea(t),await d(t);"preview"===this.s&&"object"!==typeof self.oh.qh?(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Gd(c),{isInWorker:!1,messagePort:k,canvas:this.G,runOnStartupFunctions:M}),this.Kd(),this.Ja=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ja,
c))}Qd(c,k){this.Lb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Kd(){this.Lb()}Lb(){const c=window.ah;c&&(c.parentElement.removeChild(c),window.ah=null)}async Hf(){const c=await R(this.jb);return{outputPort:c,transferables:[c]}}yf(){if(this.ca)throw Error("not available in worker mode");return this.Ja}uc(c,k,l,p,u){this.qa.postMessage({type:"event",
component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}yd(c,k,l,p,u){const r=J++,t=new Promise((z,H)=>{G.set(r,{resolve:z,reject:H})});this.qa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.Mf(c);if("result"===k)this.fg(c);else if("runtime-ready"===k)this.gg();else if("alert-error"===k)this.Lb(),alert(c.message);else if("creating-runtime"===k)this.Kd();else throw Error(`unknown message '${k}'`);
}Mf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Kb(u,!1,""+t);return}if(null===u)return r;r&&r.then?r.then(t=>this.Kb(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Kb(u,!1,""+t)}):this.Kb(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Kb(c,
k,l){let p;l&&l.transferables&&(p=l.transferables);this.qa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}fg(c){const k=c.responseId,l=c.isOk;c=c.result;const p=G.get(k);l?p.resolve(c):p.reject(c);G.delete(k)}C(c,k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static xb(c){if(F.includes(c))throw Error("DOM handler already added");F.push(c)}Fd(){for(const c of this.Sb)if("runtime"===c.ab){this.Oa=c;return}throw Error("cannot find runtime DOM handler");
}Yf(c){this.uc("debugger","message",c)}gg(){for(const c of this.Sb)c.pd()}static Va(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||g)}static Mb(c){g=!!c}gf(c){this.Ma.push(c);this.Qc()}tg(c){c=this.Ma.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ma.splice(c,1);this.Ma.length||this.Ac()}Qc(){-1===this.Na&&this.Ma.length&&(this.Na=requestAnimationFrame(this.Zg))}Ac(){-1!==this.Na&&(cancelAnimationFrame(this.Na),this.Na=-1)}bg(){this.Na=
-1;for(const c of this.Ma)c();this.Qc()}xa(c){this.Oa.xa(c)}Da(c){this.Oa.Da(c)}Pc(){this.Oa.Pc()}Eb(c){this.Oa.Eb(c)}Re(){return!!B["audio/webm; codecs=opus"]}async Sg(c){c=await this.yd("runtime","opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}$e(){this.ae=!0}Pe(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}xd(c){return!this.Pe(c)}async Ea(c){return"cordova"===this.s&&(c.startsWith("file:")||this.hb&&this.xd(c))?(c.startsWith(this.F)&&
(c=c.substr(this.F.length)),c=await this.yb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async Gf(c){const k=c.filename;switch(c.as){case "text":return await this.Ie(k);case "buffer":return await this.yb(k);default:throw Error("unsupported type");}}sd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async Ie(c){c=await this.sd(c);return await D(c)}Bc(){if(y.length&&
!(8<=C)){C++;var c=y.shift();this.nf(c.filename,c.kh,c.dh)}}yb(c){return new Promise((k,l)=>{y.push({filename:c,kh:p=>{C--;this.Bc();k(p)},dh:p=>{C--;this.Bc();l(p)}});this.Bc()})}async nf(c,k,l){try{const p=await this.sd(c),u=await x(p);k(u)}catch(p){l(p)}}Rc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");
}async mf(){const c=[];for(const [k,l]of Object.entries(this.ia))c.push(this.lf(k,l));await Promise.all(c)}async lf(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Yb[c]=k.str;else{let l=await this.wf(k);l||(l=this.qf(k));this.ia[c]=l}}async wf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}qf(c){c=this.ng(c);return this.kf(c.data,c.gh)}ng(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{gh:c,data:l}}kf(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,z;for(z=t=0;t<p;++t)r[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=
3;l--;)u[z]=c.charCodeAt(z),++z;return new Blob([u],{type:k})}}}"use strict";
{const f=self.va;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},h={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((g,m)=>{const c=document.createElement("link");c.onload=()=>g(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function w(e){return new Promise((g,m)=>{const c=new Image;c.onload=()=>g(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await w(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((g,m)=>{let c=new FileReader;c.onload=k=>g(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function x(e,g,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",g+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function y(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const g=e.getBoundingClientRect();document.body.removeChild(e);return[g.width,
g.height]}};self.C3_RasterSvgImageBlob=async function(e,g,m,c,k){e=await x(e,g,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,g,m);return l};let J=!1;document.addEventListener("pause",()=>J=!0);document.addEventListener("resume",()=>J=!1);function M(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.xb(class extends self.Sa{constructor(e){super(e,"runtime");this.be=!0;this.Pa=-1;this.kd="any";this.Rd=this.Sd=!1;this.za=
null;this.Xd="";this.Xc=-1;this.Ia=this.rb=null;this.dc=this.cc=0;this.ge=e.oa();this.Wb=e.fa();this.tb=0;e.C("canvas","update-size",c=>this.jg(c));e.C("runtime","invoke-download",c=>this.Wf(c));e.C("runtime","raster-svg-image",c=>this.cg(c));e.C("runtime","get-svg-image-size",c=>this.Uf(c));e.C("runtime","set-target-orientation",c=>this.hg(c));e.C("runtime","register-sw",()=>this.eg());e.C("runtime","post-to-debugger",c=>this.Md(c));e.C("runtime","go-to-script",c=>this.Md(c));e.C("runtime","before-start-ticking",
()=>this.Ff());e.C("runtime","debug-highlight",c=>this.If(c));e.C("runtime","enable-device-orientation",()=>this.jf());e.C("runtime","enable-device-motion",()=>this.hf());e.C("runtime","add-stylesheet",c=>this.Ef(c));e.C("runtime","alert",c=>this.Hc(c));e.C("runtime","hide-cordova-splash",()=>this.Vf());e.C("runtime","set-exporting-to-video",c=>this.zg(c));e.C("runtime","export-to-video-progress",c=>this.Nf(c));e.C("runtime","exported-to-video",c=>this.Of(c));const g=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",c=>{const k=c.target;g.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=e.G;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.ob=
0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.kg());window.addEventListener("fullscreenchange",()=>this.Xa());window.addEventListener("webkitfullscreenchange",()=>this.Xa());window.addEventListener("mozfullscreenchange",()=>this.Xa());window.addEventListener("fullscreenerror",c=>this.Kc(c));window.addEventListener("webkitfullscreenerror",
c=>this.Kc(c));window.addEventListener("mozfullscreenerror",c=>this.Kc(c));if(e.tc())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const k=window.visualViewport.height;k>c&&(document.scrollingElement.scrollTop=0);c=k})}else window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||
"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.mg(c);this.Ka=new Set;this.Zb=new WeakSet;this.pa=!1}Ff(){"cordova"===this.u.s?(document.addEventListener("pause",()=>this.Oc(!0)),document.addEventListener("resume",()=>this.Oc(!1))):document.addEventListener("visibilitychange",()=>this.Oc(document.hidden));return{isSuspended:!(!document.hidden&&!J)}}pd(){window.addEventListener("focus",()=>this.Za("window-focus"));window.addEventListener("blur",()=>
{this.Za("window-blur",{parentHasFocus:M()});this.ob=0});window.addEventListener("focusin",g=>{g=g.target;(C.has(g.tagName.toLowerCase())||y(g))&&this.Za("keyboard-blur")});window.addEventListener("keydown",g=>this.Ld("keydown",g));window.addEventListener("keyup",g=>this.Ld("keyup",g));window.addEventListener("dblclick",g=>this.Lc("dblclick",g,d));window.addEventListener("wheel",g=>this.$f(g));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",g=>{this.Ec(g);this.Ya("pointerdown",
g)}),this.u.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.rb=new self.Xe(()=>this.tf(),5),this.rb.Vd=!0,window.addEventListener("pointerrawupdate",g=>this.ag(g))):window.addEventListener("pointermove",g=>this.Ya("pointermove",g)),window.addEventListener("pointerup",g=>this.Ya("pointerup",g)),window.addEventListener("pointercancel",g=>this.Ya("pointercancel",g))):(window.addEventListener("mousedown",g=>{this.Ec(g);this.Mc("pointerdown",g)}),window.addEventListener("mousemove",
g=>this.Mc("pointermove",g)),window.addEventListener("mouseup",g=>this.Mc("pointerup",g)),window.addEventListener("touchstart",g=>{this.Ec(g);this.Jb("pointerdown",g)}),window.addEventListener("touchmove",g=>this.Jb("pointermove",g)),window.addEventListener("touchend",g=>this.Jb("pointerup",g)),window.addEventListener("touchcancel",g=>this.Jb("pointercancel",g)));const e=()=>this.Pc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",
e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.u.Qe()&&!this.u.wd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.Ic(this.fa(),navigator.virtualKeyboard.boundingRect.height)}))}Ic(e,g){document.body.style.transform="";if(0<g){var m=document.activeElement;m&&(m=m.getBoundingClientRect(),e=(m.top+m.bottom)/2-(e-g)/2,e>g&&(e=g),0>e&&(e=0),0<e&&(document.body.style.transform=
`translateY(${-e}px)`))}}Za(e,g){v(this,e,g||null,n)}oa(){return this.u.oa()}fa(){return this.u.fa()}kg(){const e=this.oa(),g=this.fa();if(this.u.wd()){if(this.ge===e&&g<this.Wb){this.tb=this.Wb-g;this.Ic(this.Wb,this.tb);return}0<this.tb&&(this.tb=0,this.Ic(g,this.tb));this.ge=e;this.Wb=g}this.Za("window-resize",{innerWidth:e,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Va()});this.u.tc()&&(-1!==this.Pa&&clearTimeout(this.Pa),this.Nd(e,g,0))}ug(e,g,m){-1!==this.Pa&&clearTimeout(this.Pa);
this.Pa=setTimeout(()=>this.Nd(e,g,m),48)}Nd(e,g,m){const c=this.oa(),k=this.fa();this.Pa=-1;c!=e||k!=g?this.Za("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Va()}):10>m&&this.ug(c,k,m+1)}hg(e){this.kd=e.targetOrientation}Og(){const e=this.kd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(e):
screen.webkitLockOrientation?g=screen.webkitLockOrientation(e):screen.mozLockOrientation?g=screen.mozLockOrientation(e):screen.msLockOrientation&&(g=screen.msLockOrientation(e));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",g)}}Xa(){const e=f.Va();e&&"any"!==this.kd&&this.Og();v(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.oa(),innerHeight:this.fa()})}Kc(e){console.warn("[Construct 3] Fullscreen request failed: ",
e);v(this,"fullscreenerror",{isFullscreen:f.Va(),innerWidth:this.oa(),innerHeight:this.fa()})}Oc(e){e?this.u.Ac():this.u.Qc();v(this,"visibilitychange",{hidden:e})}Ld(e,g){"Backspace"===g.key&&A(g);const m=b.get(g.code)||g.code;E(this,e,{code:m,key:g.key,which:g.which,repeat:g.repeat,altKey:g.altKey,ctrlKey:g.ctrlKey,metaKey:g.metaKey,shiftKey:g.shiftKey,timeStamp:g.timeStamp},d)}$f(e){v(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,
deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Lc(e,g,m){a(g)||E(this,e,{button:g.button,buttons:g.buttons,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,timeStamp:g.timeStamp},m)}Mc(e,g){if(!a(g)){var m=this.ob;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==g.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:g.button,buttons:g.buttons,lastButtons:m,clientX:g.clientX,clientY:g.clientY,
pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:g.timeStamp},d);this.ob=g.buttons;this.Lc(g.type,g,h)}}Ya(e,g){if(this.rb&&"pointermove"!==e){var m=this.rb;m.gb||(N(m),m.Vb=Date.now())}m=0;"mouse"===g.pointerType&&(m=this.ob);E(this,e,{pointerId:g.pointerId,pointerType:g.pointerType,button:g.button,buttons:g.buttons,lastButtons:m,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,
movementX:(g.movementX||0)+this.cc,movementY:(g.movementY||0)+this.dc,width:g.width||0,height:g.height||0,pressure:g.pressure||0,tangentialPressure:g.tangentialPressure||0,tiltX:g.tiltX||0,tiltY:g.tiltY||0,twist:g.twist||0,timeStamp:g.timeStamp},d);this.dc=this.cc=0;"mouse"===g.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Lc(m,g,h),this.ob=g.buttons)}ag(e){this.Ia&&(this.cc+=this.Ia.movementX||0,this.dc+=this.Ia.movementY||0);this.Ia=e;e=this.rb;
if(-1===e.Qa){var g=Date.now(),m=g-e.Vb,c=e.Ug;m>=c&&e.Vd?(e.Vb=g,e.gb=!0,e.Uc(),e.gb=!1):e.Qa=self.setTimeout(e.qe,Math.max(c-m,4))}}tf(){this.Ya("pointermove",this.Ia);this.Ia=null}Jb(e,g){for(let m=0,c=g.changedTouches.length;m<c;++m){const k=g.changedTouches[m];E(this,e,{pointerId:k.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:2*(k.radiusX||k.webkitRadiusX||
0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:g.timeStamp},d)}}Ec(e){window!==window.top&&window.focus();this.Jd(e.target)&&document.activeElement&&!this.Jd(document.activeElement)&&document.activeElement.blur()}Jd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}jf(){this.Sd||(this.Sd=!0,window.addEventListener("deviceorientation",e=>this.Kf(e)),window.addEventListener("deviceorientationabsolute",
e=>this.Lf(e)))}hf(){this.Rd||(this.Rd=!0,window.addEventListener("devicemotion",e=>this.Jf(e)))}Kf(e){v(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Lf(e){v(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}Jf(e){let g=null;var m=e.acceleration;m&&(g=
{x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});v(this,"devicemotion",{acceleration:g,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},d)}jg(e){var g=this.u;g.ae||(g=g.G,g.style.width=e.styleWidth+"px",g.style.height=e.styleHeight+"px",g.style.marginLeft=e.marginLeft+"px",g.style.marginTop=e.marginTop+"px",this.be&&
(g.style.display="",this.be=!1))}Wf(e){const g=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=g;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async cg(e){var g=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);g=g?await createImageBitmap(e,g):await createImageBitmap(e);return{imageBitmap:g,transferables:[g]}}async Uf(e){return await self.C3_GetSvgImageSize(e.blob)}async Ef(e){await q(e.url)}Pc(){var e=
[...this.Ka];this.Ka.clear();if(!this.pa)for(const g of e)(e=g.play())&&e.catch(()=>{this.Zb.has(g)||this.Ka.add(g)})}xa(e){if("function"!==typeof e.play)throw Error("missing play function");this.Zb.delete(e);let g;try{g=e.play()}catch(m){this.Ka.add(e);return}g&&g.catch(()=>{this.Zb.has(e)||this.Ka.add(e)})}Da(e){this.Ka.delete(e);this.Zb.add(e)}Eb(e){this.pa=!!e}Vf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}If(e){if(e.show){this.za||(this.za=document.createElement("div"),
this.za.id="inspectOutline",document.body.appendChild(this.za));var g=this.za;g.style.display="";g.style.left=e.left-1+"px";g.style.top=e.top-1+"px";g.style.width=e.width+2+"px";g.style.height=e.height+2+"px";g.textContent=e.name}else this.za&&(this.za.style.display="none")}eg(){window.C3_RegisterSW&&window.C3_RegisterSW()}Md(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}Cf(e,g){return this.u.yd(this.ab,"js-invoke-function",{name:e,params:g},void 0,void 0)}Hc(e){alert(e.message)}mg(e){"entered-fullscreen"===
e?(f.Mb(!0),this.Xa()):"exited-fullscreen"===e?(f.Mb(!1),this.Xa()):console.warn("Unknown wrapper message: ",e)}zg(e){const g=document.createElement("h1");g.id="exportToVideoMessage";g.textContent=e.message;document.body.prepend(g);document.body.classList.add("exportingToVideo");this.u.G.style.display="";this.u.$e()}Nf(e){this.Xd=e.message;-1===this.Xc&&(this.Xc=setTimeout(()=>this.uf(),250))}uf(){this.Xc=-1;const e=document.getElementById("exportToVideoMessage");e&&(e.textContent=this.Xd)}Of(e){window.sh({type:"exported-video",
blob:e.blob,time:e.time})}})}"use strict";async function P(f){if(f.Tg)throw Error("already initialised");f.Tg=!0;var a=f.hc.Dc("dispatchworker.js");f.Wc=await f.hc.nc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.ad=a.port1;f.Wc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.hd=await R(f)}function Q(f){return[f.ad,f.hd]}
async function R(f){const a=f.de.length;var b=f.hc.Dc("jobworker.js");b=await f.hc.nc(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,h=new MessageChannel;f.Wc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":h.port2},[d.port2,h.port2]);f.de.push(b);return h.port1}
self.Te=class{constructor(f){this.hc=f;this.F=f.F;this.F="preview"===f.s?this.F+"workers/":this.F+f.ic;this.Wg=Math.min(navigator.hardwareConcurrency||2,16);this.Wc=null;this.de=[];this.hd=this.ad=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.va({lh:!0,mh:"workermain.js",Ra:["scripts/c3runtime.js"],lc:[],md:"",ih:"scripts/",od:["box2d.wasm.js"],re:"windows-webview2"}));"use strict";
{const f=180/Math.PI;self.da=class extends self.Sa{constructor(a){super(a,"audio");this.Rb=this.c=null;this.Tb=this.$c=!1;this.sa=()=>this.Pg();this.$=[];this.D=[];this.ha=null;this.ee="";this.fe=-1;this.qb=new Map;this.ed=1;this.pa=!1;this.ld=0;this.jc=1;this.Yc=0;this.ie="HRTF";this.Wd="inverse";this.je=600;this.he=1E4;this.le=1;this.Zd=this.jd=!1;this.oe=this.u.Re();this.aa=new Map;this.Ga=new Set;this.bd=!1;this.fd="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Zf(b,d);this.Qb=null;
self.C3Audio_GetOutputStream=()=>this.Tf();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.pf(b)],["play",b=>this.og(b)],["stop",b=>this.Mg(b)],["stop-all",()=>this.Ng()],["set-paused",b=>this.Fg(b)],["set-volume",b=>this.Kg(b)],["fade-volume",b=>this.vf(b)],["set-master-volume",b=>this.Dg(b)],["set-muted",b=>this.Eg(b)],["set-silent",b=>this.Hg(b)],["set-looping",b=>this.Cg(b)],["set-playback-rate",b=>this.Gg(b)],["seek",b=>this.vg(b)],["preload",b=>this.pg(b)],["unload",b=>
this.Qg(b)],["unload-all",()=>this.Rg()],["set-suspended",b=>this.Ig(b)],["get-suspended",()=>this.zf()],["add-effect",b=>this.Dd(b)],["set-effect-param",b=>this.yg(b)],["remove-effects",b=>this.rg(b)],["tick",b=>this.ig(b)],["load-state",b=>this.Xf(b)]])}async pf(a){a.isiOSCordova&&(this.jd=!0);this.ld=a.timeScaleMode;this.ie=["equalpower","HRTF","soundfield"][a.panningModel];this.Wd=["linear","inverse","exponential"][a.distanceModel];this.je=a.refDistance;this.he=a.maxDistance;this.le=a.rolloffFactor;
var b={latencyHint:a.latencyHint};this.oe||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.c=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.c=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.Ed();this.c.onstatechange=()=>{"running"!==this.c.state&&this.Ed()};this.Rb=this.c.createGain();this.Rb.connect(this.c.destination);b=a.listenerPos;this.c.listener.setPosition(b[0],b[1],b[2]);this.c.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=
()=>this.oc();try{await Promise.all(a.preloadList.map(d=>this.Hb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.c.sampleRate}}Ed(){this.Tb||(this.$c=!1,window.addEventListener("pointerup",this.sa,!0),window.addEventListener("touchend",this.sa,!0),window.addEventListener("click",this.sa,!0),window.addEventListener("keydown",this.sa,!0),this.Tb=!0)}rf(){this.Tb&&(this.$c=!0,window.removeEventListener("pointerup",this.sa,!0),
window.removeEventListener("touchend",this.sa,!0),window.removeEventListener("click",this.sa,!0),window.removeEventListener("keydown",this.sa,!0),this.Tb=!1)}Pg(){if(!this.$c){var a=this.c;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.rf()}}W(){return this.c}oc(){return this.c.currentTime}ta(){return this.Rb}ud(a){return(a=this.aa.get(a.toLowerCase()))?a[0].P():this.ta()}se(a,
b){a=a.toLowerCase();let d=this.aa.get(a);d||(d=[],this.aa.set(a,d));b.Bg(d.length);b.Jg(a);d.push(b);this.Pd(a)}Pd(a){let b=this.ta();const d=this.aa.get(a);if(d&&d.length){b=d[0].P();for(let h=0,n=d.length;h<n;++h){const q=d[h];h+1===n?q.S(this.ta()):q.S(d[h+1].P())}}for(const h of this.ma(a))h.Ye(b);this.Aa&&this.fd===a&&(this.Aa.disconnect(),this.Aa.connect(b))}Ab(){return this.ed}Bb(){return this.pa}Ag(){this.Zd=!0}Ke(a,b){return b?this.u.Sg(a).then(d=>{const h=this.c.createBuffer(1,d.length,
48E3);h.getChannelData(0).set(d);return h}):new Promise((d,h)=>{this.c.decodeAudioData(a,d,h)})}xa(a){this.u.xa(a)}Da(a){this.u.Da(a)}zd(a){let b=0;for(let d=0,h=this.D.length;d<h;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.f():++b}this.D.length=b}Ze(){let a=0;for(let b=0,d=this.$.length;b<d;++b){const h=this.$[b];this.$[a]=h;h.ua()?h.f():++a}this.$.length=a}*ma(a){if(a)for(const b of this.D)self.da.Le(b.Y,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Hb(a,b,d,h,n){for(const q of this.$)if(q.Ua()===
b)return await S(q),q;if(n)return null;h&&(this.jd||this.Zd)&&this.Ze();n="audio/webm; codecs=opus"===d&&!this.oe;h&&n&&this.Ag();a=!h||this.jd||n?new self.Ge(this,a,b,d,h,n):new self.Ee(this,a,b,d,h);this.$.push(a);await S(a);return a}async Cc(a,b,d,h,n){for(const q of this.D)if(q.Ua()===b&&(q.mc()||n))return q.bf(h),q;a=await this.Hb(a,b,d,n);h="html5"===a.Sc?new self.Fe(a.i,a,h):new self.He(a.i,a,h);this.D.push(h);return h}ff(a){let b=this.qb.get(a);if(!b){let d=null;b={nd:0,hh:new Promise(h=>
d=h),resolve:d};this.qb.set(a,b)}b.nd++}sg(a){const b=this.qb.get(a);if(!b)throw Error("expected pending tag");b.nd--;0===b.nd&&(b.resolve(),this.qb.delete(a))}zc(a){a||(a=this.ee);return(a=this.qb.get(a))?a.hh:Promise.resolve()}Ib(){if(0<this.Ga.size)L(this);else for(const a of this.D)if(a.vd()){L(this);break}}wa(){for(var a of this.Ga)a.wa();a=this.oc();for(var b of this.D)b.wa(a);b=this.D.filter(d=>d.vd()).map(d=>d.Ta());v(this,"state",{tickCount:this.fe,audioInstances:b,analysers:[...this.Ga].map(d=>
d.Ne())});0===b.length&&0===this.Ga.size&&this.Ub&&(this.u.tg(this.pe),this.Ub=!1)}vc(a,b,d){v(this,"trigger",{type:a,tag:b,aiid:d})}async og(a){const b=a.originalUrl,d=a.url,h=a.type,n=a.isMusic,q=a.tag,w=a.isLooping,B=a.vol,D=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.c.getOutputTimestamp?(a=this.c.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.c.currentTime);this.ee=q;this.ff(q);try{this.ha=await this.Cc(b,d,h,q,n),x?(this.ha.Db(!0),this.ha.af(x.x,
x.y,x.angle,x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ha.cf(x.uid)):this.ha.Db(!1),this.ha.Play(w,B,D,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.sg(q)}L(this)}Mg(a){a=a.tag;for(const b of this.ma(a))b.na()}Ng(){for(const a of this.D)a.na()}Fg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Wa():d.Cb();this.Ib()}Kg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Fb(a)}async vf(a){const b=a.tag,d=a.vol,
h=a.duration;a=a.stopOnEnd;await this.zc(b);for(const n of this.ma(b))n.Me(d,h,a);this.Ib()}Dg(a){this.ed=a.vol;for(const b of this.D)b.Ob()}Eg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.Ad(a)}Hg(a){this.pa=a.isSilent;this.u.Eb(this.pa);for(const b of this.D)b.Nb()}Cg(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.xc(a)}async Gg(a){const b=a.tag;a=a.rate;await this.zc(b);for(const d of this.ma(b))d.Cd(a)}async vg(a){const b=a.tag;a=a.pos;await this.zc(b);for(const d of this.ma(b))d.wc(a)}async pg(a){const b=
a.originalUrl,d=a.url,h=a.type;a=a.isMusic;try{await this.Cc(b,d,h,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async Qg(a){if(a=await this.Hb("",a.url,a.type,a.isMusic,!0))a.f(),a=this.$.indexOf(a),-1!==a&&this.$.splice(a,1)}Rg(){for(const a of this.$)a.f();this.$.length=0}Ig(a){a=a.isSuspended;!a&&this.c.resume&&this.c.resume();for(const b of this.D)b.yc(a);a&&this.c.suspend&&this.c.suspend()}zf(){return this.c?this.c.state:"suspended"}ig(a){this.jc=a.timeScale;this.Yc=
a.gameTime;this.fe=a.tickCount;if(0!==this.ld)for(var b of this.D)b.Fa();(b=a.listenerPos)&&this.c.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const h of this.D)h.ga===a&&h.Bd(d.x,d.y,d.angle)}}async Dd(a){var b=a.type;const d=a.tag;var h=a.params;if("filter"===b)h=new self.ye(this,...h);else if("delay"===b)h=new self.we(this,...h);else if("convolution"===b){b=null;try{b=await this.Hb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}h=new self.ve(this,b.Z,...h);h.wg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)h=new self.ze(this,...h);else if("phaser"===b)h=new self.Be(this,...h);else if("gain"===b)h=new self.Ae(this,...h);else if("tremolo"===b)h=new self.De(this,...h);else if("ringmod"===b)h=new self.Ce(this,...h);else if("distortion"===b)h=new self.xe(this,...h);else if("compressor"===b)h=new self.ue(this,...h);else if("analyser"===b)h=new self.te(this,...h);else throw Error("invalid effect type");this.se(d,
h);this.Od()}yg(a){const b=a.index,d=a.param,h=a.value,n=a.ramp,q=a.time;a=this.aa.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,h,n,q),this.Od())}rg(a){a=a.tag.toLowerCase();const b=this.aa.get(a);if(b&&b.length){for(const d of b)d.f();this.aa.delete(a);this.Pd(a)}}ef(a){this.Ga.add(a);this.Ib()}qg(a){this.Ga.delete(a)}Od(){this.bd||(this.bd=!0,Promise.resolve().then(()=>this.sf()))}sf(){const a={};for(const [b,d]of this.aa)a[b]=d.map(h=>h.Ta());v(this,"fxstate",{fxstate:a});this.bd=!1}async Xf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.ua()&&1===b||(d.ua()||2!==b)&&d.na();for(const h of this.aa.values())for(const n of h)n.f();this.aa.clear();this.jc=a.timeScale;this.Yc=a.gameTime;d=a.listenerPos;this.c.listener.setPosition(d[0],d[1],d[2]);this.pa=a.isSilent;this.u.Eb(this.pa);this.ed=a.masterVolume;d=[];for(const h of Object.values(a.effects))d.push(Promise.all(h.map(n=>this.Dd(n))));await Promise.all(d);await Promise.all(a.playing.map(h=>this.Df(h,b)));this.Ib()}async Df(a,b){if(3!==
b){var d=a.bufferOriginalUrl,h=a.bufferUrl,n=a.bufferType,q=a.isMusic,w=a.tag,B=a.isLooping,D=a.volume,x=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.Cc(d,h,n,w,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.We(a.pan);b.Play(B,D,x,0);a.isPlaying||b.Wa();b.Gc(a)}}}Zf(a,b){this.Aa&&this.Aa.disconnect();this.fd=b.toLowerCase();this.Aa=this.c.createMediaStreamSource(a);this.Aa.connect(this.ud(this.fd))}Tf(){this.Qb||(this.Qb=this.c.createMediaStreamDestination(),
this.Rb.connect(this.Qb));return this.Qb.stream}static Le(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static df(a){return a*f}static Je(a){return Math.pow(10,a/20)}static td(a){return Math.max(Math.min(self.da.Je(a),1),0)}static Ve(a){return Math.log(a)/Math.log(10)*20}static Ue(a){return self.da.Ve(Math.max(Math.min(a,1),0))}static bh(a,b){return 1-Math.exp(-b*a)}};self.va.xb(self.da)}"use strict";function S(f){f.Xb||(f.Xb=f.Fc());return f.Xb}
self.qd=class{constructor(f,a,b,d,h){this.i=f;this.Yg=a;this.Ba=b;this.R=d;this.Vg=h;this.Sc="";this.Xb=null}f(){this.Xb=this.i=null}Fc(){}W(){return this.i.W()}qc(){return this.Yg}Ua(){return this.Ba}pc(){return this.R}ua(){return this.Vg}ea(){}};"use strict";
self.Ee=class extends self.qd{constructor(f,a,b,d,h){super(f,a,b,d,h);this.Sc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.kb=this.lb=null;this.K.addEventListener("canplaythrough",()=>!0);this.pb=this.W().createGain();this.nb=null;this.K.addEventListener("canplay",()=>{this.lb&&(this.lb(),this.kb=this.lb=null);!this.nb&&this.K&&(this.nb=this.W().createMediaElementSource(this.K),this.nb.connect(this.pb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Ba}' error: `,n);this.kb&&(this.kb(n),this.kb=this.lb=null)})}f(){this.i.zd(this);this.pb.disconnect();this.pb=null;this.nb.disconnect();this.nb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.f()}Fc(){return new Promise((f,a)=>{this.lb=f;this.kb=a;this.K.src=this.Ba})}O(){return this.K}ea(){return this.K.duration}};"use strict";
async function T(f){if(f.ya)return f.ya;var a=f.i.u;if("cordova"===a.s&&a.xd(f.Ba)&&a.hb)f.ya=await a.yb(f.Ba);else{a=await fetch(f.Ba);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function U(f){if(f.Z)return f.Z;f.Z=await f.i.Ke(f.ya,f.Xg);f.ya=null}
self.Ge=class extends self.qd{constructor(f,a,b,d,h,n){super(f,a,b,d,h);this.Sc="webaudio";this.Z=this.ya=null;this.Xg=!!n}f(){this.i.zd(this);this.Z=this.ya=null;super.f()}async Fc(){try{await T(this),await U(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ba}': `,f)}}ea(){return this.Z?this.Z.duration:0}};"use strict";
{let f=0;self.rd=class{constructor(a,b,d){this.i=a;this.L=b;this.Y=d;this.Pb=f++;this.M=this.W().createGain();this.M.connect(this.ta());this.B=null;this.ib=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.I=!0;this.V=this.la=this.H=!1;this.ub=1;this.Ha=!1;this.ra=1;a=this.i.ld;this.dd=1===a&&!this.ua()||2===a;this.eb=this.ga=-1;this.ne=!1}f(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ta(){return this.i.ud(this.Y)}Ab(){return this.i.Ab()}zb(){return this.dd?
this.i.Yc:performance.now()/1E3}qc(){return this.L.qc()}Ua(){return this.L.Ua()}pc(){return this.L.pc()}ua(){return this.L.ua()}bf(a){this.Y=a}T(){}mc(){}IsPlaying(){return!this.I&&!this.H&&!this.T()}vd(){return!this.I&&!this.T()}Ca(){}ea(){return this.L.ea()}Play(){}na(){}Wa(){}Cb(){}Fb(a){this.ub=a;this.M.gain.cancelScheduledValues(0);this.eb=-1;this.M.gain.value=this.rc()}Me(a,b,d){if(!this.Ha){a*=this.Ab();var h=this.M.gain;h.cancelScheduledValues(0);var n=this.i.oc();b=n+b;h.setValueAtTime(h.value,
n);h.linearRampToValueAtTime(a,b);this.ub=a;this.eb=b;this.ne=d}}Ob(){this.Fb(this.ub)}wa(a){-1!==this.eb&&a>=this.eb&&(this.eb=-1,this.ne&&this.na(),this.i.vc("fade-ended",this.Y,this.Pb))}rc(){const a=this.ub*this.Ab();return isFinite(a)?a:0}Ad(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Nb())}Bb(){return this.i.Bb()}Nb(){}xc(){}Cd(a){this.ra!==a&&(this.ra=a,this.Fa())}Fa(){}wc(){}yc(){}Db(a){a=!!a;this.ib!==a&&((this.ib=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.ie,this.B.distanceModel=
this.i.Wd,this.B.refDistance=this.i.je,this.B.maxDistance=this.i.he,this.B.rolloffFactor=this.i.le),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ta())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ta())))}af(a,b,d,h,n,q){this.ib&&(this.Bd(a,b,d),a=self.da.df,this.B.coneInnerAngle=a(h),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}Bd(a,b,d){this.ib&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}cf(a){this.ga=a}sc(){}Ye(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ta(){return{aiid:this.Pb,tag:this.Y,duration:this.ea(),volume:this.ub,isPlaying:this.IsPlaying(),playbackTime:this.Ca(),playbackRate:this.ra,uid:this.ga,bufferOriginalUrl:this.qc(),bufferUrl:"",bufferType:this.pc(),isMusic:this.ua(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.sc(),pan:this.Oe()}}Gc(a){this.Cd(a.playbackRate);this.Ad(a.isMuted)}Oe(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}We(a){if(a){this.Db(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Db(!1)}}}"use strict";
self.Fe=class extends self.rd{constructor(f,a,b){super(f,a,b);this.L.pb.connect(this.M);this.L.onended=()=>this.Jc()}f(){this.na();this.L.pb.disconnect();super.f()}O(){return this.L.O()}Jc(){this.I=!0;this.ga=-1;this.i.vc("ended",this.Y,this.Pb)}T(){return this.O().ended}mc(){return this.I?!0:this.T()}Ca(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Fb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(h){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ua()}' to position '${b}': `,h)}this.i.xa(d);this.H=this.I=!1;this.V=f;this.ra=1}na(){const f=this.O();f.paused||f.pause();this.i.Da(f);this.I=!0;this.H=!1;this.ga=-1}Wa(){if(!(this.H||this.I||this.T())){var f=this.O();f.paused||f.pause();this.i.Da(f);this.H=!0}}Cb(){!this.H||this.I||this.T()||(this.i.xa(this.O()),this.H=!1)}Nb(){this.O().muted=this.Ha||this.Bb()}xc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Fa(){let f=this.ra;this.dd&&(f*=this.i.jc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}wc(f){if(!this.I&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}sc(){return this.Ca()}yc(f){f?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.xa(this.O()),this.la=!1)}};"use strict";
function V(f){f.j&&f.j.disconnect();f.j=null;f.$a=null}
self.He=class extends self.rd{constructor(f,a,b){super(f,a,b);this.j=null;this.$b=d=>this.Jc(d);this.Zc=!0;this.$a=null;this.N=this.ac=this.bc=0;this.gd=1}f(){this.na();V(this);this.$b=null;super.f()}Jc(f){this.H||this.la||f.target!==this.$a||(this.I=this.Zc=!0,this.ga=-1,V(this),this.i.vc("ended",this.Y,this.Pb))}T(){return!this.I&&this.j&&this.j.loop||this.H?!1:this.Zc}mc(){return!this.j||this.I?!0:this.T()}Ca(){let f;f=this.H?this.N:this.ac+(this.zb()-this.bc)*this.ra;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,d){this.gd=1;this.Fb(a);V(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.Z;this.j.connect(this.M);this.$a=this.j;this.j.onended=this.$b;this.j.loop=f;this.j.start(d,b);this.H=this.I=this.Zc=!1;this.V=f;this.ra=1;this.bc=this.zb();this.ac=b}na(){if(this.j)try{this.j.stop(0)}catch(f){}this.I=!0;this.H=!1;this.ga=-1}Wa(){this.H||this.I||this.T()||(this.N=this.Ca(),this.V&&(this.N%=this.ea()),this.H=!0,this.j.stop(0))}Cb(){!this.H||this.I||this.T()||(V(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.$b,this.j.loop=this.V,this.Ob(),this.Fa(),this.j.start(0,this.N),this.bc=this.zb(),this.ac=this.N,this.H=!1)}rc(){return super.rc()*this.gd}Nb(){this.gd=this.Ha||this.Bb()?0:1;this.Ob()}xc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Fa(){let f=this.ra;this.dd&&(f*=this.i.jc);this.j&&(this.j.playbackRate.value=f)}wc(f){this.I||this.T()||(this.H?this.N=f:(this.Wa(),this.N=f,this.Cb()))}sc(){return this.N}yc(f){f?
this.IsPlaying()?(this.la=!0,this.N=this.Ca(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(V(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.$b,this.j.loop=this.V,this.Ob(),this.Fa(),this.j.start(0,this.N),this.bc=this.zb(),this.ac=this.N,this.la=!1)}Gc(f){super.Gc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.c=a.W();this.$d=-1;this.R=this.Y="";this.g=null}f(){this.c=null}Bg(a){this.$d=a}Jg(a){this.Y=a}o(){return this.c.createGain()}P(){}S(){}m(a,b,d,h){a.cancelScheduledValues(0);if(0===h)a.value=b;else{var n=this.c.currentTime;h+=n;switch(d){case 0:a.setValueAtTime(b,h);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,h);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,h)}}}Ta(){return{type:this.R,tag:this.Y,params:this.g}}}
self.ye=class extends f{constructor(a,b,d,h,n,q,w){super(a);this.R="filter";this.g=[b,d,h,n,q,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.A=this.c.createBiquadFilter();this.A.type=b;this.A.frequency.value=d;this.A.detune.value=h;this.A.Q.value=n;this.A.gain.vlaue=q;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b)}f(){this.l.disconnect();this.A.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,h);this.m(this.a.gain,1-b,d,h);break;case 1:this.g[1]=b;this.m(this.A.frequency,b,d,h);break;case 2:this.g[2]=b;this.m(this.A.detune,b,d,h);break;case 3:this.g[3]=b;this.m(this.A.Q,b,d,h);break;case 4:this.g[4]=b,this.m(this.A.gain,b,d,h)}}};self.we=class extends f{constructor(a,b,d,h){super(a);this.R="delay";this.g=[b,d,h];this.l=
this.o();this.b=this.o();this.b.gain.value=h;this.a=this.o();this.a.gain.value=1-h;this.mb=this.o();this.U=this.c.createDelay(b);this.U.delayTime.value=b;this.cb=this.o();this.cb.gain.value=d;this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b);this.mb.connect(this.U);this.U.connect(this.cb);this.cb.connect(this.mb)}f(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.mb.disconnect();this.U.disconnect();this.cb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){const n=self.da.td;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,h);this.m(this.a.gain,1-b,d,h);break;case 4:this.g[1]=n(b);this.m(this.cb.gain,n(b),d,h);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,h)}}};self.ve=class extends f{constructor(a,b,d,h){super(a);this.R="convolution";this.g=[d,h];this.Ud=this.Td="";this.l=this.o();this.b=this.o();this.b.gain.value=h;this.a=this.o();this.a.gain.value=
1-h;this.bb=this.c.createConvolver();this.bb.normalize=d;this.bb.buffer=b;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b)}f(){this.l.disconnect();this.bb.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,h),this.m(this.a.gain,1-b,d,h)}}wg(a,b){this.Td=a;this.Ud=b}Ta(){const a=
super.Ta();a.bufferOriginalUrl=this.Td;a.bufferUrl="";a.bufferType=this.Ud;return a}};self.ze=class extends f{constructor(a,b,d,h,n,q){super(a);this.R="flanger";this.g=[b,d,h,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.fb=this.o();this.fb.gain.value=n;this.U=this.c.createDelay(b+d);this.U.delayTime.value=b;this.v=this.c.createOscillator();this.v.frequency.value=h;this.J=this.o();this.J.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.fb);this.fb.connect(this.U);this.v.connect(this.J);this.J.connect(this.U.delayTime);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.U.disconnect();this.v.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();this.fb.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,h);this.m(this.a.gain,1-b/2,d,h);break;case 6:this.g[1]=b/1E3;this.m(this.J.gain,b/1E3,d,h);break;case 7:this.g[2]=b;this.m(this.v.frequency,b,d,h);break;case 8:this.g[3]=b/100,this.m(this.fb.gain,b/100,d,h)}}};self.Be=class extends f{constructor(a,b,d,h,n,q,w){super(a);this.R="phaser";this.g=[b,d,h,n,q,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.A=this.c.createBiquadFilter();this.A.type="allpass";this.A.frequency.value=b;this.A.detune.value=
d;this.A.Q.value=h;this.v=this.c.createOscillator();this.v.frequency.value=q;this.J=this.o();this.J.gain.value=n;this.l.connect(this.A);this.l.connect(this.a);this.A.connect(this.b);this.v.connect(this.J);this.J.connect(this.A.frequency);this.v.start(0)}f(){this.v.stop(0);this.l.disconnect();this.A.disconnect();this.v.disconnect();this.J.disconnect();this.a.disconnect();this.b.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,h);this.m(this.a.gain,1-b/2,d,h);break;case 1:this.g[0]=b;this.m(this.A.frequency,b,d,h);break;case 2:this.g[1]=b;this.m(this.A.detune,b,d,h);break;case 3:this.g[2]=b;this.m(this.A.Q,b,d,h);break;case 6:this.g[3]=b;this.m(this.J.gain,b,d,h);break;case 7:this.g[4]=b,this.m(this.v.frequency,b,d,h)}}};self.Ae=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,h){const n=self.da.td;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,h)}}};self.De=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.v=this.c.createOscillator();this.v.frequency.value=b;this.J=this.o();this.J.gain.value=d/2;this.v.connect(this.J);this.J.connect(this.h.gain);this.v.start(0)}f(){this.v.stop(0);this.v.disconnect();
this.J.disconnect();this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,h);this.m(this.J.gain,b/2,d,h);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,h)}}};self.Ce=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.sb=this.o();this.sb.gain.value=
0;this.v=this.c.createOscillator();this.v.frequency.value=b;this.v.connect(this.sb.gain);this.v.start(0);this.l.connect(this.sb);this.l.connect(this.a);this.sb.connect(this.b)}f(){this.v.stop(0);this.v.disconnect();this.sb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.f()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,h);
this.m(this.a.gain,1-b,d,h);break;case 7:this.g[0]=b,this.m(this.v.frequency,b,d,h)}}};self.xe=class extends f{constructor(a,b,d,h,n,q){super(a);this.R="distortion";this.g=[b,d,h,n,q];this.l=this.o();this.fc=this.o();this.ec=this.o();this.xg(h,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.kc=this.c.createWaveShaper();this.Vc=new Float32Array(65536);this.xf(b,d);this.kc.curve=this.Vc;this.l.connect(this.fc);this.l.connect(this.a);this.fc.connect(this.kc);this.kc.connect(this.ec);
this.ec.connect(this.b)}f(){this.l.disconnect();this.fc.disconnect();this.kc.disconnect();this.ec.disconnect();this.b.disconnect();this.a.disconnect();super.f()}xg(a,b){.01>a&&(a=.01);this.fc.gain.value=a;this.ec.gain.value=Math.pow(1/a,.6)*b}xf(a,b){for(let d=0;32768>d;++d){let h=d/32768;h=this.Lg(h,a,b);this.Vc[32768+d]=h;this.Vc[32768-d-1]=-h}}Lg(a,b,d){d=1.05*d*b-b;const h=0>a?-a:a;return(h<b?h:b+d*self.da.bh(h-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,h),this.m(this.a.gain,1-b,d,h)}}};self.ue=class extends f{constructor(a,b,d,h,n,q){super(a);this.R="compressor";this.g=[b,d,h,n,q];this.h=this.c.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=h;this.h.attack.value=n;this.h.release.value=q}f(){this.h.disconnect();super.f()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.te=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.c.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Yd=new Float32Array(this.h.frequencyBinCount);this.me=new Uint8Array(b);this.ke=this.La=0;this.i.ef(this)}f(){this.i.qg(this);this.h.disconnect();super.f()}wa(){this.h.getFloatFrequencyData(this.Yd);this.h.getByteTimeDomainData(this.me);const a=this.h.fftSize;let b=this.La=0;for(var d=0;d<a;++d){let h=(this.me[d]-128)/128;0>h&&(h=-h);
this.La<h&&(this.La=h);b+=h*h}d=self.da.Ue;this.La=d(this.La);this.ke=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ne(){return{tag:this.Y,index:this.$d,peak:this.La,rms:this.ke,binCount:this.h.frequencyBinCount,freqBins:this.Yd}}}}"use strict";
{let f=!1;self.va.xb(class extends self.Sa{constructor(a){super(a,"gamepad");this.ce=!!navigator.getGamepads;this.cd=!1;I(this,"is-supported",()=>this.ce);I(this,"ready",()=>this.dg());I(this,"vibrate",b=>this.Sf(b));I(this,"reset-vibrate",b=>this.Rf(b));window.addEventListener("gamepadconnected",b=>this.Pf(b));window.addEventListener("gamepaddisconnected",b=>this.Qf(b));window.addEventListener("unload",()=>this.lg())}Gb(){try{return Array.from(navigator.getGamepads()).filter(a=>a&&a.connected)}catch(a){return f||
(console.warn("[Construct 3] Failed to access gamepads: ",a),f=!0),[]}}dg(){this.cd=!0;for(const a of this.Gb())v(this,"gamepad-connected",{index:a.index,id:a.id});this.ce&&L(this)}Pf(a){this.cd&&(a=a.gamepad,v(this,"gamepad-connected",{index:a.index,id:a.id}))}Qf(a){this.cd&&v(this,"gamepad-disconnected",{index:a.gamepad.index})}wa(){var a=this.Gb();a.length&&(a=a.map(b=>({index:b.index,id:b.id,buttons:b.buttons.map(d=>({pressed:d.pressed,value:d.value})),axes:b.axes})),v(this,"input-update",a))}Hd(a){for(const b of this.Gb())if(b.index===
a)return b;return null}async Sf(a){var b=this.Hd(a.index);if(b&&(b=b.vibrationActuator)&&b.playEffect)try{await b.playEffect("dual-rumble",{duration:a.duration,startDelay:0,weakMagnitude:a.weakMag,strongMagnitude:a.strongMag})}catch(d){console.warn("[Gamepad] Failed to vibrate gamepad: ",d)}}Rf(a){(a=this.Hd(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()}lg(){for(const a of this.Gb()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}}})}"use strict";
function W(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>v(f,"sw-message",a.data))}
function X(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.va.xb(class extends self.Sa{constructor(f){super(f,"browser");this.s="";K(this,[["get-initial-state",a=>{this.s=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
W(this)],["alert",a=>this.Hc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Nc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>X(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,
"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.rh||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.va.Mb(!0),this.u.Rc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===
a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.va.Mb(!1),this.u.Rc({type:"set-fullscreen",
fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{v(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{v(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{v(this,"hashchange",
{location:location.toString()})});document.addEventListener("backbutton",()=>{v(this,"backbutton")})}Hc(f){alert(f.message)}Nc(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});
